old_votes_path: ./old_votes

newsletter:
  enabled: false
  target_title: User:1F616EMO/條目評選每日簡報/新條目評選
  send_mode: direct
  summary: '發送新條目評選每日簡報'

telegram:
  enabled: false
  bot_token: '123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11'
  chats:
    -123456789:
      enabled: false
    987654321:
      enabled: false
